export const settingsStyles = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  },
  sectionTitle: {
    fontSize: '0.75rem',
    fontWeight: '700',
    letterSpacing: '1.5px',
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase',
    marginBottom: '0.75rem',
    paddingLeft: '4px',
  },
  card: {
    background: 'var(--bg-surface)',
    border: '1px solid var(--border-default)',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    gap: '1rem',
    transition: 'all 0.2s',
  },
  itemText: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  itemTitle: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
    margin: 0,
  },
  itemDesc: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
    margin: 0,
    lineHeight: '1.4',
  },
  icon: {
    width: '40px',
    height: '40px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  divider: {
    height: '1px',
    background: 'var(--border-subtle)',
    margin: '0 1.25rem',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
    padding: '1rem',
  },
  statsCard: {
    background: 'rgba(255, 255, 255, 0.03)',
    padding: '12px',
    borderRadius: '12px',
    border: '1px solid var(--border-subtle)',
  },
  input: {
    padding: '10px 14px',
    borderRadius: '10px',
    background: 'var(--bg-input)',
    border: '1px solid var(--border-default)',
    color: 'var(--text-primary)',
    fontSize: '0.85rem',
    outline: 'none',
    transition: 'all 0.2s',
  },
  button: {
    padding: '10px 16px',
    borderRadius: '10px',
    fontWeight: '600',
    fontSize: '0.85rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  }
};
